default:
  tags:
    - vbox
    
build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - touch stage-build.txt

test-job1:
  stage: test
  script:
    - echo "This job tests something"
    - touch stage-test1.txt

test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20
    - touch stage-test2.txt

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    - touch stage-deploy.txt
  environment: production