##
## For keywords and structure look at https://docs.gitlab.com/ee/ci/yaml/
##
default:
  tags:
    - cplusplus
    - vbox

# Order of stages for jobs to perform in.
stages:
  - make
  - build-test
  - test
  - build
  - deploy

variables:
  TEST_TARGET: "hello-world-test"
  RUN_TARGET: "hello-world"

################################ Linux GNU Compiler ###########################

# Job for creating the make-file using the build.sh script calling CMake with appropriate arguments.
# Also wiping the cmake-build-??? directory.
job-make-gnu:
  stage: make
  cache:
    key: make-bin-gnu
    paths:
      - cmake-build-*-gnu/
  script:
    - ./build.sh -Cm .

# Job for test builds using the build.sh script calling CMake with appropriate arguments.
job-build-test-gnu:
  stage: build-test
  needs: [job-make-gnu]
  cache:
    key: make-bin-gnu
    paths:
      - cmake-build-*-gnu/
      - bin/
  script:
    - ./build.sh -b . $TEST_TARGET

job-test-gnu:
  stage: test
  needs: [job-build-test-gnu]
  cache:
    key: make-bin-gnu
    paths:
      - cmake-build-*-gnu/
      - bin/
  script:
    - ./bin/$TEST_TARGET.bin

# Jobs for building the actual run target using the build.sh script calling CMake with appropriate arguments.
job-build-gnu:
  stage: build
  needs: [job-make-gnu]
  cache:
    key: make-bin-gnu
    paths:
      - cmake-build-*-gnu/
      - bin/
  script:
    - ./build.sh -b . $RUN_TARGET

################################ Linux GW Compiler ############################

# Job for creating the make-file using the build.sh script calling CMake with appropriate arguments.
job-make-gw:
  stage: make
  cache:
    key: make-bin-gw
    paths:
      - cmake-build-*-gw/
      - binwin/
  script:
    - ./build.sh -wm .

# Job for test builds using the build.sh script calling CMake with appropriate arguments.
job-build-test-gw:
  stage: build-test
  needs: [job-make-gw]
  cache:
    key: make-bin-gw
    paths:
      - cmake-build-*-gw/
      - binwin/
  script:
    - ./build.sh -wb . $TEST_TARGET

job-test-gw:
  stage: test
  needs: [job-build-test-gw]
  cache:
    key: make-bin-gw
    paths:
      - cmake-build-*-gw/
      - binwin/
  script:
    - wine64 ./binwin/$TEST_TARGET.exe

# Job for building using the build.sh script calling CMake with appropriate arguments.
job-build-gw:
  stage: build
  needs: [job-make-gw]
  cache:
    key: make-bin-gw
    paths:
      - cmake-build-*-gw/
      - binwin/
  script:
    - ./build.sh -wb . $RUN_TARGET

###############################################################################

job-deploy-linux:
  stage: deploy
  cache:
    key: make-bin-gw
    paths:
      - cmake-build-*-gnu/
  environment: production
  script:
    - ls -la cmake-build-*-*/bin
    - echo ssh -o StrictHostKeyChecking=no -i ~/.ssh/public-key-file root@my-deplay-server
    - echo ssh -o StrictHostKeyChecking=no -i $SSH_KEY_FILE root@my-deplay-server "
      git -C /home/sites/app/
      "
