include:
  - local: ".gitlab/common-c++.gitlab-ci.yml"
  - local: ".gitlab/gnu-c++.gitlab-ci.yml"
  - local: ".gitlab/gw-c++.gitlab-ci.yml"

default:
  tags:
    - cplusplus

job-check:
  extends: .tpl-env-dump
  stage: check

