include:
  # Include Linux common jobs.
  - local: ".gitlab/lnx/tpl.gitlab-ci.yml"
    rules:
      - if: '$CI_COMMIT_BRANCH =~ /^.+-lnx-.+$/'
  # Include Windows common jobs.
  - local: ".gitlab/win/tpl.gitlab-ci.yml"
    rules:
      - if: '$CI_COMMIT_BRANCH =~ /^.+-win-.+$/'

# Order of stages for jobs to perform in.
stages:
  # Jobs checking the environment requirements.
  - check
  # Jobs producing makefiles using CMake
  - make
  # Jobs for building the actual run target and possible dynamic libraries using.
  - build
  # Jobs for building tests using dynamic libraries of the build.
  - build-test
  # Jobs executing the build (unit-)tests.
  - test
  # Jobs for deploying of stored artifacts.
  - deploy

# Defaults for all jobs.
default:
  # Tags determine the selection of a runner.
  tags:
    # Variables 'SF_TARGET_OS' and 'SF_TARGET_ARCH' depends on the include-file
    # which on its turn depends on the commit branch name.
    - cplusplus
    - "${SF_TARGET_OS}"
    - "${SF_TARGET_ARCH}"

# Template to deploy only when having on the release branch.
.tpl-deploy:
  rules:
    - if: $CI_COMMIT_BRANCH == $SF_RELEASE_BRANCH_NAME

