include:
  # Include GNU compiler jobs for Linux for branches amd64 and arm64.
  - local: ".gitlab/lnx/gnu/jobs.gitlab-ci.yml"
    rules:
      - if: '$CI_COMMIT_BRANCH =~ /^.+-lnx-(arm64|amd64)$/'
  # Include GW cross-compiler jobs for Linux specific amd64 branches.
  - local: ".gitlab/lnx/gw/jobs.gitlab-ci.yml"
    rules:
      - if: '$CI_COMMIT_BRANCH =~ /^.+-lnx-amd64$/'

# Obligatory in this setup of jobs depending on or needs it.
# Reports the environment vars set for the job.
job-check-lnx:
  # Common template job.
  extends: .tpl-env-dump-lnx
  stage: check

