# Some variables used to config this include-file.
variables:
  # Output directory.
  SF_DIR_BIN_MINGW: "bin/win64"
  # Fixed directory the source root is mounted to.
  SF_DIR_MOUNT_MINGW: "${BIND_DIR}/${CI_COMMIT_SHORT_SHA}-mingw"

# Template to mount source root on a fixed directory path for Windows MinGW compiler.
.tpl-bind-mingw:
  before_script:
    # Log to syslog to be able to see execution flow.
    - echo "${SF_LOG_TAG}" "Mounting '${SF_DIR_MOUNT_GNU}' => '$(pwd)'"
  after_script:
    # Log to syslog to be able to see execution flow.
    - echo "${SF_LOG_TAG}" "Unmounting '${SF_DIR_MOUNT_GNU}' =>  '$(pwd)'"

# Template to configure cache for CMake generated files for the GW compiler.
.tpl-cache-mingw:
  cache:
    key: "${CI_COMMIT_REF_NAME}.${CI_COMMIT_SHORT_SHA}-mingw"
    paths:
      - cmake-build-*/

# Template to define artifacts in the designated directory.
.tpl-artifacts-mingw:
  artifacts:
    name: "${CI_COMMIT_REF_NAME}-mingw"
    expire_in: 2 days
    paths:
      - "${SF_DIR_BIN_MINGW}"
