# Template to dump all environment variables.
.tpl-env-dump-win:
  # Do not need the cache for this one.
  cache: []
  before_script:
    - 'Write-Host (-Join ("Username=", [System.Security.Principal.WindowsIdentity]::GetCurrent().Name))'
    - 'Write-Host (-Join ("Working Directory=", (Get-Location).Path))'
    - 'Write-Host (Get-ChildItem Env: | Format-Table | Out-String)'
  script:
    - 'Write-Host "..."'

# Template to reference to for the single Windows script line only.
.tpl-log-win-script:
  script:
    # Log to Windows event log to be able to see execution flow.
    - 'Write-EventLog -LogName "Application" -Source "gitlab-runner" -EventID 1000 -EntryType Information -Message ([System.String]::Concat("${SF_LOG_TAG} ", (Get-Location).Path))'
